***Variables***
${TODOLIST.LOGO.FRAME}                       //h1[text()="To Do List"]           
${ADDITEM.ADDTAB.TABMENU}                    //a[contains(@class,'mdl-tabs__tab')][text()="Add Item"]
${ADDITEM.INPUTLIST.TEXTBOX}                 //input[@id="new-task"]
${ADDITEM.ADDLIST.BUTTON}                   //button[contains(@class,'mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab mdl-button--colored')]
    