***Variables***
${COMPLETETASK.COMPLETETAB.TABMENU}                    //a[contains(@class,'mdl-tabs__tab')][text()="Completed"]
${COMPLETETASK.COMPLETELIST.TEXT}                      //span[contains(@class,'mdl-list__item-primary-content')][text()="{list_name}"]
${COMPLETETASK.LISTDONE.MATERIAL}                      //i[contains(@class,'material-icons mdl-list__item-icon')]
${COMPLETETASK.DELETELISTDONE.MATERIAL}                //span[contains(@class,'mdl-list__item-primary-content')][text()="{list_name}"]//following-sibling::button
